data = read.csv("semiautomatically-results.tsv", sep="\t")
summary(data)
data$CompleteRatio = data$Complete/(data$Complete+data$Incomplete+data$Unknown)
library(tidyr)
library(dplyr)
data %>% filter(Noun == "fact") %>% summarise(CompleteRatio = mean(CompleteRatio))
data %>% filter(Noun == "report") %>% summarise(CompleteRatio = mean(CompleteRatio))
data %>% filter(Noun == "story") %>% summarise(CompleteRatio = mean(CompleteRatio))
data %>% filter(Noun == "admission") %>% summarise(CompleteRatio = mean(CompleteRatio))
data %>% filter(Noun == "belief") %>% summarise(CompleteRatio = mean(CompleteRatio))
data %>% filter(Noun == "complaint") %>% summarise(CompleteRatio = mean(CompleteRatio))
data %>% filter(Noun == "assumption") %>% summarise(CompleteRatio = mean(CompleteRatio))
data %>% group_by(Noun == "assumption") %>% summarise(CompleteRatio = mean(CompleteRatio))
u = data %>% group_by(Noun) %>% summarise(CompleteRatio = mean(CompleteRatio))
u[order(u$CompleteRatio),]
print(u[order(u$CompleteRatio),], n=50)
                                                                                                          
counts = read.csv("../../../../forgetting/fromCorpus_counts.csv", sep="\t")
                                                                                               
counts$Ratio = counts$True_False - counts$False_False                                  
                                                                                                                                    
data = merge(u, counts, by=c("Noun"), all.x=TRUE)
cor(data$Ratio, data$CompleteRatio)
cor.test(data$Ratio, data$CompleteRatio)
cor.test(data$Ratio, log(data$CompleteRatio))
library(lme4)
data = read.csv("semiautomatically-results.tsv", sep="\t")
data$CompleteRatio = data$Complete/(data$Complete+data$Incomplete+data$Unknown)
data = merge(data, counts, by=c("Noun"), all.x=TRUE)
summary(lmer(CompleteRatio ~ Ratio + (1|ID), data=data))
summary(lmer(CompleteRatio ~ Ratio + (1+Ratio|ID), data=data))
summary(lmer(CompleteRatio ~ Ratio + DeletionRate + (1+Ratio|ID), data=data))
summary(lmer(CompleteRatio ~ Ratio + DeletionRate + PredictabilityWeight + (1+Ratio|ID), data=data))
summary(data$Unknown/(data$Complete+data$Incomplete+data$Unknown))
data$UnknownRatio = (data$Unknown/(data$Complete+data$Incomplete+data$Unknown))
data %>% filter(UnknownRatio > 0.6)
data$CompleteRatio = data$Complete/(data$Complete+data$Incomplete)
summary(lmer(CompleteRatio ~ Ratio + DeletionRate + PredictabilityWeight + (1+Ratio|ID) + (1|Noun), data=data))
#savehistory("semiautomatic.R")
